# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='info.proto',
  package='info',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ninfo.proto\x12\x04info\"\x17\n\x03Req\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"_\n\x04Info\x12\x0e\n\x06\x62\x61nkno\x18\x01 \x01(\t\x12\r\n\x05money\x18\x02 \x01(\x02\x12\x0c\n\x04\x62\x61nk\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x0e\n\x06remark\x18\x05 \x01(\t\x12\x0c\n\x04time\x18\x06 \x01(\t\"$\n\x07\x41rrInfo\x12\x19\n\x05\x41info\x18\x01 \x03(\x0b\x32\n.info.Info\"]\n\x03Rsp\x12#\n\x0cvillagesInfo\x18\x01 \x03(\x0b\x32\r.info.ArrInfo\x12 \n\totherInfo\x18\x02 \x01(\x0b\x32\r.info.ArrInfo\x12\x0f\n\x07\x65rrCode\x18\x03 \x01(\x08\x32\x31\n\x0eGetInfoService\x12\x1f\n\x07GetInfo\x12\t.info.Req\x1a\t.info.Rspb\x06proto3'
)




_REQ = _descriptor.Descriptor(
  name='Req',
  full_name='info.Req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='info.Req.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=43,
)


_INFO = _descriptor.Descriptor(
  name='Info',
  full_name='info.Info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bankno', full_name='info.Info.bankno', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='money', full_name='info.Info.money', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bank', full_name='info.Info.bank', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='info.Info.name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='remark', full_name='info.Info.remark', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='info.Info.time', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=140,
)


_ARRINFO = _descriptor.Descriptor(
  name='ArrInfo',
  full_name='info.ArrInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Ainfo', full_name='info.ArrInfo.Ainfo', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=178,
)


_RSP = _descriptor.Descriptor(
  name='Rsp',
  full_name='info.Rsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='villagesInfo', full_name='info.Rsp.villagesInfo', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='otherInfo', full_name='info.Rsp.otherInfo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='errCode', full_name='info.Rsp.errCode', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=273,
)

_ARRINFO.fields_by_name['Ainfo'].message_type = _INFO
_RSP.fields_by_name['villagesInfo'].message_type = _ARRINFO
_RSP.fields_by_name['otherInfo'].message_type = _ARRINFO
DESCRIPTOR.message_types_by_name['Req'] = _REQ
DESCRIPTOR.message_types_by_name['Info'] = _INFO
DESCRIPTOR.message_types_by_name['ArrInfo'] = _ARRINFO
DESCRIPTOR.message_types_by_name['Rsp'] = _RSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Req = _reflection.GeneratedProtocolMessageType('Req', (_message.Message,), {
  'DESCRIPTOR' : _REQ,
  '__module__' : 'info_pb2'
  # @@protoc_insertion_point(class_scope:info.Req)
  })
_sym_db.RegisterMessage(Req)

Info = _reflection.GeneratedProtocolMessageType('Info', (_message.Message,), {
  'DESCRIPTOR' : _INFO,
  '__module__' : 'info_pb2'
  # @@protoc_insertion_point(class_scope:info.Info)
  })
_sym_db.RegisterMessage(Info)

ArrInfo = _reflection.GeneratedProtocolMessageType('ArrInfo', (_message.Message,), {
  'DESCRIPTOR' : _ARRINFO,
  '__module__' : 'info_pb2'
  # @@protoc_insertion_point(class_scope:info.ArrInfo)
  })
_sym_db.RegisterMessage(ArrInfo)

Rsp = _reflection.GeneratedProtocolMessageType('Rsp', (_message.Message,), {
  'DESCRIPTOR' : _RSP,
  '__module__' : 'info_pb2'
  # @@protoc_insertion_point(class_scope:info.Rsp)
  })
_sym_db.RegisterMessage(Rsp)



_GETINFOSERVICE = _descriptor.ServiceDescriptor(
  name='GetInfoService',
  full_name='info.GetInfoService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=275,
  serialized_end=324,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetInfo',
    full_name='info.GetInfoService.GetInfo',
    index=0,
    containing_service=None,
    input_type=_REQ,
    output_type=_RSP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GETINFOSERVICE)

DESCRIPTOR.services_by_name['GetInfoService'] = _GETINFOSERVICE

# @@protoc_insertion_point(module_scope)
